name: GenAI Issue Labeller
on:
  issues:
    types: [opened, reopened, edited]
permissions:
  contents: read
  issues: write
  models: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  blink:
    runs-on: ubuntu-latest
    steps:
      - name: React with blink emoji
        run: gh api -X POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions -f content="blush"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  genai-issue-labeller:
    needs: blink
    runs-on: ubuntu-latest
    steps:
      - uses: pelikhan/action-genai-issue-labeller@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}